### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'is_Function'

### ISSUE THREAD

**Issue by nottoday-9** [wukan1986/alpha_examples#5]
Traceback (most recent call last):
  File "project_deap\gp_run\main.py",line 883, in <module>    
    population, logbook, hof = main() 
                               ^^^^^^ 
  File "project_deap\gp_run\main.py", line 768, in main        
    population, logbook = eaMuPlusLambda(pop, toolbox,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project_deap\gp_base_cs\deap_patch.py", line 256, in eaMuPlusLambda
    fitnesses = toolbox.map(toolbox.evaluate, invalid_ind)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project_deap\gp_run\main.py", line 687, in map_exprs   
    new_results= batched_exprs(batch_id, dict(exprs_batched), g, label,df_input,split_date)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "project_deap\expr_codegen\tool.py", line 192, in all
    exprs_ldl, G = self.dag(True)
                   ^^^^^^^^^^^^^^
File "project_deap\expr_codegen\tool.py", line 140, in dag
    children = get_children(func, func_kwargs, expr, [], syms)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project_deap\expr_codegen\expr.py", line 227, in get_children    
    curr = func(expr, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project_deap\expr_codegen\expr.py", line 151, in get_current_by_prefix
    if expr.is_Function:
       ^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'is_Function'

想问下这个地方报错的原因，感谢

**Comment by wukan1986** [comment]
抱歉，才看到，由于项目太多，每天通知邮件非常多，常常错过，建议发了issue后在微信群里提示我去看一下。

这里就是表达式有问题，变成了元组。
如果你能每次都能复现，最好下断点或打印，看是哪个表达式有问题
